# fly.toml app configuration file generated for gh-org-actions on 2024-11-07T18:02:34-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gh-org-actions'
primary_region = 'sjc'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
